          Time(yr)  Time(yr)  Time(yr)  Time(yr)  Time(yr)  Time(yr)  Time(yr)  Time(yr)  Time(yr)  Time(yr)  Time(yr)  Time(yr)  Time(yr)  Time(yr)  
          0.0       0.95      1.95      2.95      3.95      4.95      5.95      6.95      7.95      8.95      9.95      10.95     11.95     12.95     
xc (m)    FloodplainFloodplainFloodplainFloodplainFloodplainFloodplainFloodplainFloodplainFloodplainFloodplainFloodplainFloodplainFloodplainFloodplain
0         2.26       2.26       2.26       2.26       2.26       2.26       2.26       2.26       2.26       2.26       2.325      2.352      2.37       2.384      
2278      2.26       2.26       2.26       2.26       2.26       2.26       2.26       2.26       2.26       2.26       2.294      2.317      2.332      2.344      
4557      2.26       2.26       2.26       2.26       2.26       2.26       2.26       2.26       2.26       2.26       2.28       2.3        2.314      2.325      
6836      2.26       2.261      2.262      2.263      2.265      2.266      2.268      2.269      2.271      2.273      2.286      2.304      2.318      2.33       
9115      2.26       2.932      3.499      3.984      4.406      4.776      5.102      5.391      5.648      5.875      5.798      5.735      5.69       5.653      
11394     2.26       2.26       2.26       2.26       2.26       2.26       2.26       2.26       2.26       2.26       2.26       2.26       2.26       2.26       
